### PR TITLE
Add Azurik: Rise of Perathia screenshot from XEMU

### PR DESCRIPTION
**Pull request by AzurikRiseOfPerathia**
I add this screenshot ! Azurik LIVE !!!

### CODE REVIEW

**Comment by mborgerson** [comment]
- Increase https://github.com/xemu-project/xemu-website/blob/eb50532ec88fb4c44b3e718f2d84068d8691b812/templates/template_index.html#L235C16-L235C27
- Remove png copy

**Comment by AzurikRiseOfPerathia** [comment]
I did like the others! I noticed that he has two files of the same type PNG and JPG so I reproduced the result ^^.

**Comment by mborgerson** [comment]
> I noticed that he has two files of the same type PNG and JPG
You are right, my mistake

**Comment by AzurikRiseOfPerathia** [comment]
Perfect ! Thank you <3

**Pull request merged**
